# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1sXlU60saS4YRkwC40jS_x3npKfjUKVzs
"""

import os
import json
import time
import concurrent.futures
import streamlit as st
from groq import Groq
import PyPDF2
import docx
from PIL import Image
import pytesseract

# --- CONFIG ---
API_KEY = "apikey"
client = Groq(api_key=API_KEY)

st.set_page_config(page_title="AI Learning Assistant", layout="wide")

# --- TEXT EXTRACTION FUNCTIONS ---
def extract_text_from_pdf(file):
    try:
        pdf_reader = PyPDF2.PdfReader(file)
        text = ""
        for page in pdf_reader.pages:
            text += page.extract_text() + "\n"
        return text[:5000]
    except Exception as e:
        return f"Error reading PDF: {str(e)}"

def extract_text_from_docx(file):
    try:
        doc = docx.Document(file)
        text = "\n".join([p.text for p in doc.paragraphs])
        return text[:5000]
    except Exception as e:
        return f"Error reading DOCX: {str(e)}"

def extract_text_from_image(file):
    try:
        image = Image.open(file)
        text = pytesseract.image_to_string(image)
        return text[:5000]
    except Exception as e:
        return f"Error reading image: {str(e)}"

def extract_text_from_txt(file):
    try:
        return file.read().decode("utf-8")[:5000]
    except Exception as e:
        return f"Error reading TXT: {str(e)}"

# --- GROQ CALL ---
def robust_groq_call(prompt, retries=2):
    for i in range(retries + 1):
        try:
            response = client.chat.completions.create(
                model="llama-3.3-70b-versatile",
                messages=[{"role": "user", "content": prompt}],
                temperature=0.3,
                max_tokens=2048
            )
            return response.choices[0].message.content
        except Exception as e:
            if i < retries:
                time.sleep(1)
                continue
            return f"❌ Error: {str(e)}"

def parallel_groq_calls(prompts):
    with concurrent.futures.ThreadPoolExecutor() as executor:
        futures = [executor.submit(robust_groq_call, p) for p in prompts]
        return [f.result() for f in futures]

# --- UI ---
st.title("📚 AI Learning Assistant")

# Sidebar inputs
topic = st.sidebar.text_input("Topic", "Core Logic")
skill = st.sidebar.selectbox("Skill Level", ["beginner", "intermediate", "advanced"])
goal = st.sidebar.text_input("Goal", "learning")

# File upload
uploaded_file = st.file_uploader("Upload document (PDF, DOCX, TXT, Image)")

document_text = ""

if uploaded_file:
    ext = uploaded_file.name.split(".")[-1].lower()

    if ext == "pdf":
        document_text = extract_text_from_pdf(uploaded_file)
    elif ext == "docx":
        document_text = extract_text_from_docx(uploaded_file)
    elif ext in ["png", "jpg", "jpeg"]:
        document_text = extract_text_from_image(uploaded_file)
    elif ext == "txt":
        document_text = extract_text_from_txt(uploaded_file)
    else:
        st.error("Unsupported file type")

    st.subheader("📄 Extracted Text")
    st.text_area("", document_text, height=200)

# --- GENERATE LESSON ---
if st.button("Generate Lesson"):
    context = f"\n\nUse this reference:\n{document_text}" if document_text else ""

    lesson_prompt = f"""
    Create a detailed {skill} lesson on '{topic}'.
    Format:
    - Overview
    - Key Concepts
    - Example
    - Summary
    {context}
    """

    plan_prompt = f"Create a 3-step study plan for {topic}. Keep concise."

    lesson, plan = parallel_groq_calls([lesson_prompt, plan_prompt])

    st.subheader("📘 Lesson")
    st.write(lesson)

    st.subheader("🧭 Study Plan")
    st.write(plan)

# --- GENERATE QUIZ ---
if st.button("Generate Quiz"):
    prompt = f"""
    Generate 5 MCQ for {topic}.
    Return JSON only.
    Format:
    [{{"q":"","options":["","","",""],"correct":0}}]
    """

    response = robust_groq_call(prompt)

    try:
        quiz = json.loads(response)
        for i, q in enumerate(quiz):
            st.write(f"**Q{i+1}: {q['q']}**")
            choice = st.radio(
                "Select answer",
                q["options"],
                key=i
            )
            if st.button(f"Check Q{i+1}", key=f"btn{i}"):
                if q["options"].index(choice) == q["correct"]:
                    st.success("Correct!")
                else:
                    st.error("Wrong!")
    except:
        st.error("Failed to parse quiz")

# --- TUTOR ---
st.subheader("🤖 Ask Tutor")
user_q = st.text_input("Ask a question")

if st.button("Get Help"):
    prompt = f"Explain simply: {user_q}"
    answer = robust_groq_call(prompt)
    st.write(answer)
